-- CreateEnum
CREATE TYPE "MedalTier" AS ENUM ('bronze', 'silver', 'gold');

-- AlterTable
ALTER TABLE "Medal" ADD COLUMN     "imageBronzeUrl" TEXT,
ADD COLUMN     "imageGoldUrl" TEXT,
ADD COLUMN     "imageSilverUrl" TEXT;

-- AlterTable
ALTER TABLE "MedalAward" ADD COLUMN     "tier" "MedalTier";

-- Catalogue officiel des médailles (ordres espacés de 10 pour pouvoir en intercaler).
-- Rôle Discord à associer dans Admin > Médailles > Catalogue.
INSERT INTO "Medal" ("id", "name", "category", "description", "imageUrl", "imageBronzeUrl", "imageSilverUrl", "imageGoldUrl", "repeatable", "order", "updatedAt") VALUES
  (gen_random_uuid()::text, 'Medal of Honor', 'Faits d’armes individuels', 'Héroïsme extraordinaire ayant changé le cours de la bataille. Historiquement : décernée pour « courage et intrépidité au péril de sa vie et au-delà du devoir ».', '/medailles/medal-of-honor.png', NULL, NULL, NULL, true, 10, NOW()),
  (gen_random_uuid()::text, 'Distinguished Service Cross', 'Faits d’armes individuels', 'Héroïsme exceptionnel avec un impact tactique majeur. Historiquement : décernée pour « héroïsme extraordinaire », une action héroïque qui ne peut justifier une Medal of Honor.', '/medailles/distinguished-service-cross.png', '/medailles/distinguished-service-cross-bronze.png', '/medailles/distinguished-service-cross-argent.png', '/medailles/distinguished-service-cross-or.png', true, 20, NOW()),
  (gen_random_uuid()::text, 'Silver Star', 'Faits d’armes individuels', 'Bravoure remarquable, grande efficacité face à l’ennemi et initiative tactique importante. Historiquement : décernée pour courage « en opération », action honorable moins importante que pour la DSC.', '/medailles/silver-star.png', '/medailles/silver-star-bronze.png', '/medailles/silver-star-argent.png', '/medailles/silver-star-or.png', true, 30, NOW()),
  (gen_random_uuid()::text, 'Distinguished Service Medal', 'Faits d’armes individuels', 'Acte de combat majeur. Historiquement : décernée pour héroïsme exceptionnel.', '/medailles/distinguished-service-medal.png', '/medailles/distinguished-service-medal-bronze.png', '/medailles/distinguished-service-medal-argent.png', '/medailles/distinguished-service-medal-or.png', true, 40, NOW()),
  (gen_random_uuid()::text, 'Bronze Star', 'Faits d’armes individuels', 'Acte de combat supérieur. Historiquement : décernée pour des actions de bravoure, d’héroïsme et de mérite moins importantes que pour la Silver Star.', '/medailles/bronze-star.png', '/medailles/bronze-star-bronze.png', '/medailles/bronze-star-argent.png', '/medailles/bronze-star-or.png', true, 50, NOW()),
  (gen_random_uuid()::text, 'Commendation Medal', 'Faits d’armes individuels', 'Acte de combat mineur. Historiquement : décernée pour des actions valeureuses, d’une importance moindre que celles justifiant la Bronze Star.', '/medailles/commendation-medal.png', '/medailles/commendation-medal-bronze.png', '/medailles/commendation-medal-argent.png', '/medailles/commendation-medal-or.png', true, 60, NOW()),
  (gen_random_uuid()::text, 'Army & Air Force Presidential Unit Citation', 'Collectives', 'Décernée à une unité pour un exploit extraordinaire changeant le cours ou l’issue de la bataille. Doit être approuvée par un chef de bataillon ou du régiment avant la remise aux récipiendaires. Historiquement : décernée par le président à une compagnie pour « héroïsme extraordinaire ».', '/medailles/presidential-unit-citation.png', NULL, NULL, NULL, true, 70, NOW()),
  (gen_random_uuid()::text, 'Meritorious Unit Commendation', 'Collectives', 'Décernée à une unité pour un acte de combat majeur. Doit être demandée ou co-demandée par un SL, le XO, le CO ou un membre de l’EM. Historiquement : récompense une unité pour des actes, au combat ou hors combat, exceptionnellement méritoires.', '/medailles/meritorious-unit-commendation.png', '/medailles/meritorious-unit-commendation-bronze.png', '/medailles/meritorious-unit-commendation-argent.png', '/medailles/meritorious-unit-commendation-or.png', true, 80, NOW()),
  (gen_random_uuid()::text, 'OP44 Campaign Medal', 'Collectives', 'Décernée à tout soldat ayant participé à 4 events OP44, à la fin de la campagne. Inspirée de la European-African-Middle Eastern Campaign Medal, qui récompensait les militaires ayant participé aux opérations des théâtres d’Europe, d’Afrique ou du Moyen-Orient.', '/medailles/op44-campaign-medal.png', NULL, NULL, NULL, false, 90, NOW()),
  (gen_random_uuid()::text, 'Case Blue Campaign Medal', 'Collectives', 'Décernée à tout soldat ayant participé à 4 events Case Blue, à la fin de la campagne. Inspirée de la médaille soviétique pour la défense du Caucase, distribuée à ceux qui y ont participé entre 1942 et 1944.', '/medailles/case-blue-campaign-medal.png', NULL, NULL, NULL, false, 100, NOW()),
  (gen_random_uuid()::text, 'Commemorative Medal for the Battle of Crete', 'Collectives', 'Décernée à tout soldat ayant participé à l’event de 8 h du 20/08/23. Inspirée de la médaille grecque décernée à ceux qui ont participé aux combats de 1940-1941 en Albanie, en Crète, en Macédoine et en Thrace.', '/medailles/battle-of-crete-medal.png', NULL, NULL, NULL, false, 110, NOW()),
  (gen_random_uuid()::text, 'Purple Heart', 'Infanterie', 'Avoir été mis hors de combat par l’ennemi pendant l’accomplissement d’une mission importante et/ou continuer à servir efficacement après avoir été réanimé ou redéployé. Historiquement : blessure subie au combat du fait de l’ennemi.', '/medailles/purple-heart.png', NULL, NULL, NULL, true, 120, NOW()),
  (gen_random_uuid()::text, 'Combat Medical Badge', 'Infanterie', 'Être assigné en tant que médic, avec plusieurs réanimations et une participation active aux combats en première ligne. Historiquement : acte de soin sous le feu de l’ennemi.', '/medailles/combat-medical-badge.png', '/medailles/combat-medical-badge-bronze.png', '/medailles/combat-medical-badge-argent.png', '/medailles/combat-medical-badge-or.png', true, 130, NOW()),
  (gen_random_uuid()::text, 'Distinguished Marksman Badge', 'Infanterie', 'Précision exceptionnelle, impact direct sur les objectifs et engagement de cibles importantes. Historiquement : obtenu pour un certain score en compétition au fusil.', '/medailles/distinguished-marksman-badge.png', '/medailles/distinguished-marksman-badge-bronze.png', '/medailles/distinguished-marksman-badge-argent.png', '/medailles/distinguished-marksman-badge-or.png', true, 140, NOW()),
  (gen_random_uuid()::text, 'Army Achievement Medal', 'Infanterie', 'Décernée au top 3 des soldats les plus actifs du mois en partie VANILLA. Historiquement : récompense les membres de l’armée pour leur conduite exemplaire.', '/medailles/army-achievement-medal.png', NULL, NULL, NULL, true, 150, NOW()),
  (gen_random_uuid()::text, 'Legion of Merit', 'Administration', 'Bonne conduite pendant 6 mois sans averto ni dossier, sous validation de l’EM. Peut être retirée par la PM ou l’EM après un averto ou un dossier. Historiquement : conduite exemplaire exceptionnelle en période de guerre.', '/medailles/legion-of-merit.png', NULL, NULL, NULL, false, 160, NOW()),
  (gen_random_uuid()::text, 'Good Conduct Medal', 'Administration', 'Bonne conduite pendant 3 mois sans averto ni dossier, sous validation de la PM. Peut être retirée par la PM ou l’EM après un averto ou un dossier. Historiquement : conduite exemplaire.', '/medailles/good-conduct-medal.png', NULL, NULL, NULL, false, 170, NOW()),
  (gen_random_uuid()::text, 'Demobilisation Patch', 'Administration', 'Passage en civil ou vétéran. Historiquement : cousu sur l’uniforme à la démobilisation du soldat.', '/medailles/demobilisation-patch.png', NULL, NULL, NULL, false, 180, NOW()),
  (gen_random_uuid()::text, 'Parachutist Badge', 'Administration', 'Décerné à la réussite de la Bleusaille. Historiquement : remis à la fin de la formation parachutiste.', '/medailles/parachutist-badge.png', NULL, NULL, NULL, false, 190, NOW()),
  (gen_random_uuid()::text, 'Community Investment Medal', 'Administration', 'Récompense l’implication dans la communauté.', '/medailles/community-investment-medal.png', NULL, NULL, NULL, true, 200, NOW())
ON CONFLICT ("name") DO NOTHING;
